const loginFields = [
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: " Name",
    labelFor: "name",
    id: "name",
    name: "name",
    type: "text",
    autoComplete: "name",
    isRequired: true,
    placeholder: "Name",
    pattern: "",
  },
  {
    labelText: "Username",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
    pattern: "",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
    pattern: "",
  },
  {
    labelText: "MobileNumber",
    labelFor: "mobilenumber",
    id: "mobilenumber",
    name: "mobilenumber",
    type: "tel",
    pattern: "[0-9]{10}",
    autoComplete: "mobilenumber",
    isRequired: true,
    placeholder: "mobile Number",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
    pattern: "",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
    pattern: "",
  },
];
const createContactFields = [
  {
    labelText: "Contact Name",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
    pattern: "",
  },
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
    pattern: "",
  },
  {
    labelText: "MobileNumber",
    labelFor: "mobilenumber",
    id: "mobilenumber",
    name: "mobilenumber",
    type: "tel",
    pattern: "[0-9]{10}",
    autoComplete: "mobilenumber",
    isRequired: true,
    placeholder: "mobile Number",
  },
  {
    labelText: "MobileNumber",
    labelFor: "mobilenumber",
    id: "mobilenumber",
    name: "mobilenumber",
    type: "tel",
    pattern: "[0-9]{10}",
    autoComplete: "mobilenumber",
    isRequired: false,
    placeholder: "mobile Number(optional)",
  },
];

export { loginFields, signupFields, createContactFields };
